export const productData = [
  {
    title: "Online-Food-Delivery-web-app",
    url: "https://github.com/sumit-kr-das/Online-Food-Delivery-web-app",
    live: "https://github.com/sumit-kr-das/Online-Food-Delivery-web-app",
    des: "Online Food Delivery Appication is a full-stack MERN tool.",
    tags: ["ReactJS", "MongoDB", "NodeJS", "ExpressJS", "api", "full-stack"],
  },
  {
    title: "short-news-reading-web-app",
    url: "https://github.com/sumit-kr-das/short-news-reading-web-app",
    live: "https://newsort.herokuapp.com/",
    des: "sort news reading web application",
    tags: [
      "html",
      "css",
      "ejs",
      "nodejs",
      "gasp",
      "api",
      "full-stack",
    ],
  },
  {
    title: "e_commerce-multivendor-website",
    url: "https://github.com/sumit-kr-das/e_commerce-multivendor-website",
    live: "https://grocy.netlify.app/pages/index.html",
    des: "A complete e-commerce website made using html, css, js",
    tags: ["html", "css", "js", "slick-slider", "swiper-js", "front-end"],
  },
  {
    title: "portfolio-smoothUI",
    url: "https://github.com/sumit-kr-das/portfolio-dg",
    live: "https://dg-portfoliosite.herokuapp.com/",
    des: "A simple portfolio website made for developers.",
    tags: ["ReactJS", "ui", "front-end", "frontend-mentor"],
  },
  {
    title: "Sudoku-puzzle",
    url: "https://github.com/Dheet-Developer-Team/Sudoku-puzzle",
    live: "https://dheet-developer-team.github.io/Sudoku-puzzle/",
    des: "Sudoku is a logic-based, combinatorial number-placement puzzle",
    tags: ["html", "css", "puzzle", "game"],
  },
  {
    title: "drawingBoard",
    url: "https://github.com/Dheet-Developer-Team/drawingBoard",
    live: "https://youthful-nobel-27f67c.netlify.app/",
    des: "WhiteBoard is tool for teacher & student both",
    tags: ["html", "css", "canvas", "tool"],
  },
  {
    title: "easybank-landing-page-master",
    url: "https://github.com/sumit-kr-das/easybank-landing-page-master",
    live: "https://cocky-almeida-fade3e.netlify.app/",
    des: "Front-end challenge by frontendmentor designed with HTML, CSS & JavaScript",
    tags: ["html", "css", "js", "front-end", "frontend-mentor"],
  },
  {
    title: "single-page-website",
    url: "https://github.com/sumit-kr-das/single-page-website",
    live: "https://wonderful-wright-25cfc5.netlify.app/",
    des: "Front-end for Marketing Agency or a Company",
    tags: ["html", "css", "js", "front-end"],
  },
  {
    title: "fylo-landing-page-with-two-column-layout-master",
    url: "https://github.com/sumit-kr-das/fylo-landing-page-with-two-column-layout-master",
    live: "https://clever-thompson-604c03.netlify.app/",
    des: "Front-end challenge by frontendmentor designed with HTML, CSS",
    tags: ["html", "css", "front-end", "frontend-mentor"],
  },
  {
    title: "payapi-multi-page-website",
    url: "https://github.com/sumit-kr-das/payapi-multi-page-website",
    live: "https://eloquent-fermi-64500d.netlify.app/",
    des: "Front-end challenge by frontend-mentor designed with HTML, CSS & JavaScript",
    tags: ["html", "css", "js", "front-end", "frontend-mentor"],
  },
];
